### ISSUE TITLE
Cycle nuit/jour Cantha

### ISSUE THREAD

**Issue by Eleazarus** [thoanny/fishing-companion#1]
Bonjour Thoanny,

Tout d'abord merci pour l'overlay déjà bien complet.
Nous constatons que le cycle jour/nuit indiqué est celui tyrien. Possible d'indiquer en plus le cycle canthien?

**Comment by thoanny** [comment]
Bonjour Eleazarus.

Le cycle affiché dépend normalement de la carte sur laquelle vous êtes connecté.

Quelques vérifications si vous pouvez :
1. Le fichier GW2MumbleLink est-il toujours présent à la racine du dossier du compagnon de pêche ?
2. Lorsque vous êtes en jeu avec le compagnon ouvert, vous avez bien un lien vert ?
3. Sur quelle carte étiez-vous au moment où vous avez constaté l'heure  tyrienne ?

Merci !

**Comment by Eleazarus** [comment]
Bonjour Thoanny,

1. Le fichier est bien présent
![image](https://user-images.githubusercontent.com/3368249/161598055-2e22d8a2-3d64-446f-9708-2f99a6e86d40.png)

2. Le lien vert l'est lui aussi
![image](https://user-images.githubusercontent.com/3368249/161598144-df280cdb-c0f1-4c32-bf4d-1dd98901af96.png)

3. Constaté Sur Seitung et Kaineng (avec d'autres guildiens utilisant l'overlay).

Nous voyons les changements de passage de jour/nuit tyrien sur les poissons disponibles dans l'overlay en coïncidence avec le timer disponible sur le wiki -> https://wiki.guildwars2.com/wiki/Day_and_night

Exemple ici sur Kaineng à 19h41, il est sur crépuscule alors que c'est déjà la nuit à Cantha.
![image](https://user-images.githubusercontent.com/3368249/161600900-9211dbf5-aece-4339-ba94-817a26884465.png)

Le timer wiki sur ces horaires :
![image](https://user-images.githubusercontent.com/3368249/161602465-3d71882e-c46b-41c5-a170-1f1a88f00af0.png)

Sur la même map à 19h45, heure de nuit tyrienne, il passe enfin en nuit.
![image](https://user-images.githubusercontent.com/3368249/161601482-295b919d-0a95-4bc7-8230-57d997eebd53.png)

**Comment by thoanny** [comment]
Merci pour ce retour détaillé. Je viens de simuler ces conditions (Néo-Kaineng et 19h41) et j'ai bien la nuit qui est affichée. Êtes-vous sûrs d'utiliser la dernière version du compagnon de pêche ?

**Comment by Eleazarus** [comment]
J'utilise la Version 0.9-beta.6 qui est la dernière disponible depuis ces 5 derniers jours. En attestent les dates de modification des fichier dans le screen du dossier au 31/03/2022, date de la mise à disposition de cette version.

**Comment by thoanny** [comment]
Merci encore ! Je viens de constater le bug. Je crée une version de debug pour pouvoir comprendre et corriger le problème.
