### ISSUE TITLE
Poisson quotidien

### ISSUE THREAD

**Issue by thoanny** [thoanny/fishing-companion#7]
Le poisson quotidien n'a rien à voir avec le succès quotidien d'EoD. C'est le poisson qu'il faut donner à Taro Serreconstante [Poissonnier] à Pierre Arborea. C'est le poisson qui s'échange une fois par jour contre un Morceau d'ambre gris ancien, et qui change tout les jours de manière aléatoire (il ne semble pas y avoir de pattern). Ca peut être le même poisson plusieurs jours d'affilés. C'est toujours un poisson rare.

Trouver un moyen, manuel, de pouvoir ajouter ce poisson (fichier texte dans le repository, à lire comme le système de version avec la date et l'ID du poisson ?)

**Comment by Blakl** [comment]
Salut. Merci pour l'outil. Cependant le poisson du jour ne semble plus remonté depuis qqs jours. J'ai uniquement les poissons correspondant à la map ou je suis.

**Comment by thoanny** [comment]
Salut ! En effet, ce n'est pas automatique mais manuel (il n'y a pas l'info dans l'API). Dans l'idée : je me réveille, je me connecte en jeu, je vais voir le PNJ, je prends le nom du poisson, je l'édite dans mes fichiers et je l'envoie en ligne. Sauf que depuis quelques jours, je passe du temps avec ma famille ;-) Je rentre mardi soir !

**Comment by Blakl** [comment]
Ha ok :) je pensais que tu avais trouvé une soluce comme je voyais ton post en fermer :) désolé et bon repos en famille ;)
