### ISSUE TITLE
Poisson du jour ?

### ISSUE THREAD

**Issue by zanagraf** [thoanny/fishing-companion#8]
HellO thoanny,

Ces derniers temps je n'ai plus le poisson du jour et c'est triste ^^ (depuis la dernière maj jeu je crois)

Merci par avance de regarder ce qui se passe !

**Comment by thoanny** [comment]
Salut :)

Ce n'est pas un bug, c'est juste que c'est une information que je mets à jour manuellement. Sauf que j'ai pris quelques jours de vacances et que j'ai difficilement accès à mon PC et une bonne connexion internet ;)

Je rentre mardi soir !
